---
#This message will be sent to the player when the player mines a special block. {reward} will be replaced by the reward price.
reward-message: "§a§l(!) §r§aCongrats! You have earned §e${reward} §afor mining this block!"

#These are the blocks the player will be rewarded for, when mined. Format:
#itemid: price
56: 150
14: 10
15: 50
16: 30
21: 20
153: 60
129: 200
...
