---
#This message will be sent to the player when the player mines a special block. {reward} will be replaced by the reward price.
reward-message: "§7(§b§l!§r§7) §r§aCongrats! You have earned §b${reward} §afor mining this block!"

#These are the blocks the player will be rewarded for, when mined. Format:
#itemid: price
56: 90
14: 5
15: 40
16: 20
21: 10
153: 30
129: 100
...
